apiVersion: apps/v1
kind: Deployment
metadata:
  name: team1-card-deployment
  namespace: group1-team1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: team1-card-deployment
  template:
    metadata:
      labels:
        app: team1-card-deployment
    spec:
      containers:
        - name: team1-card-deployment
          image: k8s-vga-worker1:5000/group1-team1-card-service:v1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: team1-card-service
  namespace: group1-team1
spec:
  selector:
    app: team1-card-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9000
      nodePort: 30140
  type: NodePort
