apiVersion: apps/v1
kind: Deployment
metadata:
  name: group1-team1-spring-boot-jenkins
  namespace: group1-team1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group1-team1-spring-boot-jenkins
  template:
    metadata:
      labels:
        app: group1-team1-spring-boot-jenkins
    spec:
      containers:
        - name: group1-team1-spring-boot-jenkins
          image: k8s-vga-worker1:5000/group1-team1-spring-boot-jenkins:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: group1-team1-spring-boot-jenkins-svc
  namespace: group1-team1
spec:
  selector:
    app: group1-team1-spring-boot-jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30115
  type: NodePort
