server:
  port: 9020

spring:
  profiles:
    active: "prod"
  application:
    name: kafka-producer-service
  cloud:
    stream:
      function:
        definition: publish
      bindings:
        publish-out-0:
          destination: input-topic
          content-type: application/json
      kafka:
        binder:
          brokers: 192.168.100.221:30192  # Kafka 브로커 주소
