server:
  port: 8090

spring:
  profiles:
    active: "prod"
  application:
    name: team1-loan-service  # 서비스 이름 (Eureka에 등록될 이름)
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true  # IP 기반 서비스 조회 (선택 사항)
  client:
    registerWithEureka: true  # Eureka Server에 서비스 등록
    fetchRegistry: true 


info:
  app:
    name: "cards"
    description: "Eazy Bank Cards Application"
    version: "1.0.0" 