server:
  port: 9200

spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          # search-locations: "file:///Users//eazybytes//Documents//config"
         git:
           uri: "https://github.com/nohdj/team1_study_repo.git"
           default-label: main
           search-paths: config  # 'config' 폴더를 바라보도록 설정
           timeout: 5
           clone-on-start: true
           force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
