apiVersion: apps/v1
kind: Deployment
metadata:
  name: team1-configserver-deployment
  namespace: group1-team1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: team1-configserver-deployment
  template:
    metadata:
      labels:
        app: team1-configserver-deployment
    spec:
      containers:
        - name: team1-configserver-deployment
          image: k8s-vga-worker1:5000/group1-team1-configserver-service:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: team1-configserver-service
  namespace: group1-team1
spec:
  selector:
    app: team1-configserver-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9200
      nodePort: 30145
  type: NodePort
