apiVersion: apps/v1
kind: Deployment
metadata:
  name: team1-gatewayserver-deployment
  namespace: group1-team1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team1-gatewayserver-deployment
  template:
    metadata:
      labels:
        app: team1-gatewayserver-deployment
    spec:
      containers:
        - name: team1-gatewayserver-deployment
          image: k8s-vga-worker1:5000/group1-team1-gatewayserver-service:v1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9202
---
apiVersion: v1
kind: Service
metadata:
  name: team1-gatewayserver-service
  namespace: group1-team1
spec:
  selector:
    app: team1-gatewayserver-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9202
      nodePort: 30146
  type: NodePort
