spring:
  config:
    import: "optional:configserver:http://localhost:9200/"
  cloud:  
    stream:  
      kafka:
          binder:
            brokers:
              - 192.168.100.221:30192      

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9201/eureka/